# Generated by Django 4.1.3 on 2022-11-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_posts_options_posts_slug_alter_posts_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['timestamp', 'updated'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
